/**
 * Handling of user-uploaded game artwork.
 *
 * Security posture, since this accepts arbitrary files from the browser:
 *  - Only raster formats are accepted. SVG is refused outright — we serve these
 *    files from our own origin, and an SVG is a script-execution vector.
 *  - Nothing the user uploaded is ever served back verbatim. Every file is
 *    decoded by sharp and re-encoded to WebP, which drops EXIF, colour profiles,
 *    trailing payloads and any polyglot trickery in the original container.
 *  - `sharp` is given an explicit pixel ceiling so a small "decompression bomb"
 *    file cannot expand into gigabytes of memory.
 *  - Output filenames are generated from a validated slug, never from the
 *    uploaded filename, so path traversal is impossible.
 *
 * Files land in data/uploads (outside the public directory, and gitignored) and
 * are served by the /uploads route.
 */

import 'server-only';
import { mkdirSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import path from 'node:path';
import sharp, { type Metadata } from 'sharp';
import { paletteFromBuffer, DEFAULT_PALETTE, type Palette } from './palette';

export const UPLOAD_DIR = process.env.STEAMDER_UPLOADS ?? path.join(process.cwd(), 'data', 'uploads');

/** Largest upload we accept, before decoding. */
export const MAX_UPLOAD_BYTES = 8 * 1024 * 1024;

/** Refuse anything that would decode to more pixels than this (~48 MP). */
const MAX_PIXELS = 48_000_000;

const ACCEPTED_MIME = new Set(['image/jpeg', 'image/png', 'image/webp', 'image/avif']);
/** What sharp reports after sniffing the actual bytes. */
const ACCEPTED_FORMAT = new Set(['jpeg', 'png', 'webp', 'avif']);

export const ACCEPT_ATTRIBUTE = 'image/jpeg,image/png,image/webp,image/avif';

/** Steam's asset geometry, reproduced. */
const TARGETS = {
  capsule: { w: 600, h: 900 },
  header: { w: 460, h: 215 },
  hero: { w: 1920, h: 620 },
} as const;

export type AssetKind = keyof typeof TARGETS;

export interface UploadResult {
  /** Filenames written under UPLOAD_DIR, one per asset kind. */
  assets: Record<AssetKind, string>;
  palette: Palette;
}

export type UploadError =
  | 'NO_FILE'
  | 'TOO_LARGE'
  | 'BAD_TYPE'
  | 'UNREADABLE'
  | 'TOO_MANY_PIXELS'
  | 'TOO_SMALL';

/** Filenames we are willing to serve: generated by us, nothing else. */
const SERVABLE = /^[a-z0-9]([a-z0-9-]{0,78}[a-z0-9])?\.webp$/;

export function isServableUploadName(name: string): boolean {
  return SERVABLE.test(name);
}

export function uploadPath(name: string): string | null {
  if (!isServableUploadName(name)) return null;
  const full = path.join(UPLOAD_DIR, name);
  // Belt and braces: the regex already forbids separators and dots.
  if (path.dirname(path.resolve(full)) !== path.resolve(UPLOAD_DIR)) return null;
  return full;
}

async function readUpload(file: File): Promise<Buffer | UploadError> {
  if (!(file instanceof File) || file.size === 0) return 'NO_FILE';
  if (file.size > MAX_UPLOAD_BYTES) return 'TOO_LARGE';
  // The declared type is a hint only; sharp's sniffing below is what decides.
  if (file.type && !ACCEPTED_MIME.has(file.type)) return 'BAD_TYPE';
  return Buffer.from(await file.arrayBuffer());
}

/**
 * Decode, validate and re-encode one upload into all three Steam asset sizes.
 *
 * `portrait`, when given, supplies the 2:3 capsule so a wide banner does not
 * have to be cropped down to a portrait shape.
 */
export async function processGameArtwork(
  slug: string,
  landscape: File,
  portrait?: File | null,
): Promise<UploadResult | UploadError> {
  const main = await readUpload(landscape);
  if (typeof main === 'string') return main;

  let cover: Buffer | null = null;
  if (portrait && portrait instanceof File && portrait.size > 0) {
    const read = await readUpload(portrait);
    if (typeof read === 'string') return read;
    cover = read;
  }

  // Validate by decoding, not by trusting the client.
  let meta: Metadata;
  try {
    meta = await sharp(main).metadata();
  } catch {
    return 'UNREADABLE';
  }
  if (!meta.format || !ACCEPTED_FORMAT.has(meta.format)) return 'BAD_TYPE';
  if (!meta.width || !meta.height) return 'UNREADABLE';
  if (meta.width * meta.height > MAX_PIXELS) return 'TOO_MANY_PIXELS';
  if (meta.width < 200 || meta.height < 100) return 'TOO_SMALL';

  if (cover) {
    try {
      const cm = await sharp(cover).metadata();
      if (!cm.format || !ACCEPTED_FORMAT.has(cm.format)) return 'BAD_TYPE';
      if (!cm.width || !cm.height) return 'UNREADABLE';
      if (cm.width * cm.height > MAX_PIXELS) return 'TOO_MANY_PIXELS';
    } catch {
      return 'UNREADABLE';
    }
  }

  mkdirSync(UPLOAD_DIR, { recursive: true });

  const assets = {} as Record<AssetKind, string>;
  for (const kind of Object.keys(TARGETS) as AssetKind[]) {
    const { w, h } = TARGETS[kind];
    const source = kind === 'capsule' && cover ? cover : main;

    const out = await sharp(source, { limitInputPixels: MAX_PIXELS })
      // Honour EXIF orientation, then discard the metadata entirely.
      .rotate()
      .resize(w, h, { fit: 'cover', position: 'attention' })
      .webp({ quality: 82 })
      .toBuffer();

    const name = `${slug}-${kind}.webp`;
    writeFileSync(path.join(UPLOAD_DIR, name), out);
    assets[kind] = name;
  }

  const palette = (await paletteFromBuffer(main)) ?? DEFAULT_PALETTE;
  return { assets, palette };
}

/** Remove every asset belonging to a slug. Safe to call when nothing exists. */
export function deleteGameArtwork(slug: string): void {
  for (const kind of Object.keys(TARGETS) as AssetKind[]) {
    const target = uploadPath(`${slug}-${kind}.webp`);
    if (target && existsSync(target)) rmSync(target, { force: true });
  }
}

export function uploadUrl(name: string): string {
  return `/uploads/${encodeURIComponent(name)}`;
}
